# Generated by Django 5.1.1 on 2024-09-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirbhik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_token',
            field=models.BooleanField(default=False),
        ),
    ]
